#!/bin/bash
echo "*** WARNING: USING LOCAL PACKER ***"

function lowercase() {
    #echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
    echo "$1" | awk '{print tolower($0)}'
}

OS="$(lowercase "$(uname -a | grep Microsoft -q && echo windowsnt || uname)")"

if [[ ! -d "packer.io/bin" ]]; then
    ./install
fi

if [[ "$OS" == "windowsnt" || "$OS" == *"mingw"* || "$OS" == *"cygwin"*  ]]; then
    "packer.io/bin/packer.exe" "$@"
else
    "packer.io/bin/packer" "$@"
fi


