#!/bin/bash

function lowercase() {
    #echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
    echo "$1" | awk '{print tolower($0)}'
}

PACKER_VERISON="1.1.3"
PACKER_FILE="packer-io.zip"

OS="$(lowercase "$(uname -a | grep Microsoft -q && echo windowsnt || uname)")"
echo "OS=${OS}"
if [[ "$OS" == "windowsnt" || "$OS" == *"mingw"* || "$OS" == *"cygwin"*  ]]; then
    OS=windows
    FILE="https://releases.hashicorp.com/packer/$PACKER_VERISON/packer_${PACKER_VERISON}_windows_amd64.zip"
elif [ "$OS" == "linux" ]; then
    OS=linux
    FILE="https://releases.hashicorp.com/packer/$PACKER_VERISON/packer_${PACKER_VERISON}_linux_amd64.zip"
elif [ "$OS" == "darwin" ]; then
    OS="mac"
    FILE="https://releases.hashicorp.com/packer/$PACKER_VERISON/packer_${PACKER_VERISON}_darwin_amd64.zip"
fi

if [ "$FILE" ]; then
    echo "Removing: ./bin"
    rm -rf ./bin

    echo "Downloading: $PACKER_FILE from $FILE"
#    wget --continue -L "$FILE" -O packer-io.zip
    curl  -o "$PACKER_FILE" "$FILE"

    if [ -f "$PACKER_FILE" ]; then
        echo "Installing: $PACKER_FILE"
        rm -rf ./bin

        if [ "$(which unzip)" == "" ]; then
            echo "UNZIP not found"
        fi

        unzip "$PACKER_FILE" -d bin
    fi
else
    echo "Nothing to do"
fi
